### ISSUE TITLE
validate syntactic section

### ISSUE THREAD

**Issue by connor-a-francis** [ourPLCC/plcc-reorg#21]
SyntacticValidator should contain an errorList, initially empty.
When validated, this errorList is populated by the validator.
The validator is composed of multiple checks.
Each check should check one property.

Syntactic checks

-Terminal names must be all upper-case letters, numbers, and underscore and cannot start with a number.
-Non-terminal names must start with a lower-case letter, and may contain upper or lower case letters, numbers, and underscore.
-Every RHS non-terminal must appear on the LHS of at least one rule.
-The resolved names for all LHS rules must be unique.
-Within a rule, the resolved names for all RHS symbols must be unique.
-User supplied names on for LHS symbols must start with a capital letter, and may contain upper or lower case letters, numbers, and underscore.
-Use supplied names for RHS symbols must start with a lower case letter, and may contain upper or lower case letters, numbers, and underscore.
-The separator for a repetition rule must be a terminal.
-All terminals must be defined as tokens in the lexical specification.

LL1 validation is currently out of the scope of this pull request.

**Comment by StoneyJackson** [comment]
@connor-a-francis  Thanks!

I recommend divide and conquer this. Pick one, do it quickly. Get feedback from me. Have others train on it. And then split the rest up and have everyone work on one or two. This could be done in one shared PR or multiple. Maybe just use a checklist here to keep track. Let's discuss tomorrow in our meeting.
