### ISSUE TITLE
Update Directory Separators in Tests

### ISSUE THREAD

**Issue by AksharP5** [ourPLCC/plcc-reorg#25]
### Problem
Tests that utilize directory separators before files are not compatible across different operating systems, as the tests fail due to them being defaulted to the format that is specified in the test. Below are examples of what I am talking about: 
```
def test_load_rough_spec(fs):
    fs.create_file('A.java', contents='hi in java')
    fs.create_file('B.py', contents='hi in python')
    fs.create_file('test.py', contents='''\
one
%
two
% java
%include /A.java 
% python
%include /B.py 
% c++
%%%
%include nope
% nope
%%%
''')
    assert load_rough_spec('test.py') == split_rough_spec([
        makeLine('one', 1, 'test.py'),
        makeDivider('%', 2, 'test.py'),
        makeLine('two', 3, 'test.py'),
        makeDivider('% java', 4, 'test.py'),
        makeLine('hi in java', 1, '/A.java'), #issue with the '/'
        makeDivider('% python', 6, 'test.py'),
        makeLine('hi in python', 1, '/B.py'), #issue with the '/'
        makeDivider('% c++', 8, 'test.py'),
        makeBlock('''
            %%%
            %include nope
            % nope
            %%%
        ''', 9, 12, 'test.py')
    ])
```
```
def test_include(fs):
    fs.create_file('/f', contents='hi')
    assert list(process_includes(parse_includes(parse_lines('%include /f')))) == [
        Line('hi', 1, '/f')
    ]
```

These tests fail on a local Windows environment, however they pass in linux and macOS environments, as the directory separator is not normalized for different operating systems, on Windows a failing test looks like this: 

```
FAILED src/plcc/load_spec/load_rough_spec/process_includes_test.py::test_include - AssertionError: assert [Line(string='hi', number=1, file='\\f')] == [Line(string='hi', number=1, file='/f')]

  At index 0 diff: Line(string='hi', number=1, file='\\f') != Line(string='hi', number=1, file='/f')

  Full diff:
    [
        Line(
            string='hi',
            number=1,
  -         file='/f',
  ?               ^
  +         file='\\f',
  ?               ^^
        ),
    ]
```

### Possible Solutions
There are two ways that I have thought about to normalize paths utilizing something such as ```os.path.normpath()```, or ```Path().as_posix()``` from pathlib, which will result in the tests passing across different operating systems. However, this issue ties in with #26  as that issue must also be resolved for all the tests to pass on Windows.

**Comment by StoneyJackson** [comment]
We only support PLCC in Linux like environments. In development, folks should be using the defined development environment, which is currently Linux through gitpod.

**Comment by AksharP5** [comment]
@StoneyJackson 

Understood, this issue may be closed in that case
