### ISSUE TITLE
AttributeError for process_include() on Windows environment

### ISSUE THREAD

**Issue by AksharP5** [ourPLCC/plcc-reorg#26]
In ```load_rough_spec.py``` the ```process_include(self, include)``` method is causing certain tests to fail on a local Windows environment, however the tests are passing on a local macOS and linux environment, as well as on GitPod. The issue occurs across these lines: 
```
if not p.is_absolute():
            if include.file.line is not None:
                p = (Path(include.line.file).parent/p).resolve()
            else:
                p = (Path.cwd()/p).resolve()
```
When you run tests via ```bin/test/units.bash``` you are informed that coverage is missing for these lines in load_rough_spec.py:
![image](https://github.com/user-attachments/assets/140652b9-ad43-47ed-9fa1-1274cd0c4444)
However all of the tests still pass on GitPod, linux, and macOS, but they fail on Windows. I am not sure why this is the case, but it has been ignored on certain operating systems. The specific issue on Windows is ```"AttributeError: 'str' object has no attribute 'line'``` regarding the line ```if include.file.line is not None```:
![image](https://github.com/user-attachments/assets/64df31f5-2b52-4575-842b-eb6ef4c934a6)

Is this meant to be written this way? As the file attribute should not have its own line attribute according to the class definition:
```
@dataclass(frozen=True)
class Include():
    file: str
    line: Line
```
This AttributeError may just be a typo, however these lines of code seem to be overlooked, because if you were to simply remove them from the function, all the tests pass (as long as the issue in #25 is also addressed), even on Windows, but if they are present, the tests pass on linux, macOS, and GitPod, but not Windows.

**Comment by StoneyJackson** [comment]
Closing for the same reason we closed #25.
