### ISSUE TITLE
Validate RHS Resolved Names and Separators

### ISSUE THREAD

**Issue by connor-a-francis** [ourPLCC/plcc-reorg#35]
Implement these validations:
- Within a rule, the resolved names for all RHS symbols must be unique.
- The separator for a repetition rule must be a terminal. </br> </br>
Inside the validate() method of the SyntacticRhsValidator class, calls to new _validateResolvedNames() and _validateSeparator() methods could be placed.
From _validateResolvedNames(), self.syntacticSpec should be accessed to resolve names and check against duplicates, appending to self.errorList when necessary.
From _validateSeparator(), self.syntacticSpec should be accessed to verify separator fields of RepeatingSyntacticRules, appending to self.errorList when necessary.

**Comment by StoneyJackson** [comment]
Split into ourPLCC/plcc-ng#1 and ourPLCC/plcc-reorg#54
